name: PHP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php:
    name: GrumPHP
    runs-on: ubuntu-latest
    container: srcoder/development-php:php82-fpm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create app/etc
        run: mkdir -p app/etc

      - name: Install Composer package
        run: composer2 install --prefer-dist --optimize-autoloader

      - name: GrumPHP
        run: vendor/bin/grumphp run
