name: PHP

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php:
    name: GrumPHP
    runs-on: ubuntu-latest
    container: srcoder/development-php:php82-fpm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Composer package
        run: composer2 install --prefer-dist -o

      - name: GrumPHP
        run: vendor/bin/grumphp run
